name: image_filters
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  loading_animations: ^2.2.0
  scroll_to_index: ^3.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy-Medium.ttf
    - family: Doto
      fonts:
        - asset: assets/fonts/Doto-Black.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Medium.ttf
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Medium.ttf
    - family: ShadowsIntoLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Medium.ttf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: RockSalt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf

